#!/usr/bin/env bash

function audit_subdomain() {
  local domain=$1
  local subdomain=$2
  local sub_domains=("www" "lb-01" "web-01" "web-02")
  local dig_output
  local record_type
  local destination

  if [ -z "$subdomain" ]; then
    for sub in "${sub_domains[@]}"; do
      dig_output=$(dig +short "$sub.$domain" | awk '/ANSWER SECTION/ {getline;print}')
      record_type=$(echo "$dig_output" | awk '{print$4}')
      destination=$(echo "$dig_output" | awk '{print$5}')
      echo "The subdomain $sub is a $record_type record and points to $destination"
    done
  else
    dig_output=$(dig +short "$subdomain.$domain" | awk '/ANSWER SECTION/ {getline;print}')
    record_type=$(echo "$dig_output" | awk '{print$4}')
    destination=$(echo "$dig_output" | awk '{print$5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
  fi
}

audit_subdomain "$1" "$2"
