#!/usr/bin/env bash
# customizing the 404 page

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello world!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/paulkelvin permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

#creating the 404 error page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo sed -i "s/listen 80 default_server;/$string_for_replace/" /etc/nginx/sites-enabled/default

sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restart nginx after implementing changes

sudo service nginx restart
